version: '3'
services:

  rabbitmq:
    image: rabbitmq:management
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - my-network

  kafka:
    container_name: kafka
    image: spotify/kafka:latest
    ports:
      - 2181:2181
      - 9092:9092
    networks:
      - my-network

  zipkin:
    image: openzipkin/zipkin
    ports:
      - 9411:9411
    networks:
      - my-network

  redis:
    image: redis
    ports:
      - 6379:6379
    networks:
      - my-network

  # nginx
  ts-ui-dashboard:
    image: maruftuhin/ts-ui-dashboard:jaeger
    restart: always
    ports:
      - 8080:8080
    networks:
      - my-network

  ts-auth-service:
    image: maruftuhin/ts-auth-service:jaeger
    restart: always
    ports:
      - 12340:12340
    networks:
      - my-network

  ts-auth-mongo:
    image: mongo
    networks:
      - my-network

  ts-user-service:
    image: maruftuhin/ts-user-service:jaeger
    restart: always
    ports:
      - 12342:12342
    networks:
      - my-network

  ts-user-mongo:
    image: mongo
    networks:
      - my-network

  ts-verification-code-service:
    image: maruftuhin/ts-verification-code-service:jaeger
    restart: always
    ports:
      - 15678:15678
    networks:
      - my-network

  ts-account-mongo:
    image: mongo
    networks:
      - my-network

  ts-route-service:
    image: maruftuhin/ts-route-service:jaeger
    restart: always
    ports:
      - 11178:11178
    networks:
      - my-network

  ts-route-mongo:
    image: mongo
    networks:
      - my-network

  ts-contacts-service:
    image: maruftuhin/ts-contacts-service:jaeger
    restart: always
    ports:
      - 12347:12347
    networks:
      - my-network

  ts-contacts-mongo:
    image: mongo
    networks:
      - my-network

  ts-order-service:
    image: maruftuhin/ts-order-service:jaeger
    restart: always
    ports:
      - 12031:12031
    networks:
      - my-network

  ts-order-mongo:
    image: mongo
    networks:
      - my-network

  ts-order-other-service:
    image: maruftuhin/ts-order-other-service:jaeger
    restart: always
    ports:
      - 12032:12032
    networks:
      - my-network

  ts-order-other-mongo:
    image: mongo
    networks:
      - my-network

  ts-config-service:
    image: maruftuhin/ts-config-service:jaeger
    restart: always
    ports:
      - 15679:15679
    networks:
      - my-network

  ts-config-mongo:
    image: mongo
    networks:
      - my-network

  ts-station-service:
    image: maruftuhin/ts-station-service:jaeger
    restart: always
    ports:
      - 12345:12345
    networks:
      - my-network

  ts-station-mongo:
    image: mongo
    networks:
      - my-network

  ts-train-service:
    image: maruftuhin/ts-train-service:jaeger
    restart: always
    ports:
      - 14567:14567
    networks:
      - my-network

  ts-train-mongo:
    image: mongo
    networks:
      - my-network

  ts-travel-service:
    image: maruftuhin/ts-travel-service:jaeger
    restart: always
    ports:
      - 12346:12346
    networks:
      - my-network

  ts-travel-mongo:
    image: mongo
    networks:
      - my-network

  ts-travel2-service:
    image: maruftuhin/ts-travel2-service:jaeger
    restart: always
    ports:
      - 16346:16346
    networks:
      - my-network

  ts-travel2-mongo:
    image: mongo
    networks:
      - my-network

  ts-preserve-service:
    image: maruftuhin/ts-preserve-service:jaeger
    restart: always
    ports:
      - 14568:14568
    networks:
      - my-network

  ts-preserve-other-service:
    image: maruftuhin/ts-preserve-other-service:jaeger
    restart: always
    ports:
      - 14569:14569
    networks:
      - my-network

  ts-basic-service:
    image: maruftuhin/ts-basic-service:jaeger
    restart: always
    ports:
      - 15680:15680
    networks:
      - my-network

  ts-ticketinfo-service:
    image: maruftuhin/ts-ticketinfo-service:jaeger
    restart: always
    ports:
      - 15681:15681
    networks:
      - my-network

  ts-price-service:
    image: maruftuhin/ts-price-service:jaeger
    restart: always
    ports:
      - 16579:16579
    networks:
      - my-network

  ts-price-mongo:
    image: mongo
    networks:
      - my-network

  ts-notification-service:
    image: maruftuhin/ts-notification-service:jaeger
    restart: always
    environment:
      - rabbitmq_host=rabbitmq
    ports:
      - 17853:17853
    networks:
      - my-network

  ts-notification-mongo:
    image: mongo
    networks:
      - my-network

  ts-security-service:
    image: maruftuhin/ts-security-service:jaeger
    restart: always
    ports:
      - 11188:11188
    networks:
      - my-network

  ts-security-mongo:
    image: mongo
    networks:
      - my-network

  ts-inside-payment-service:
    image: maruftuhin/ts-inside-payment-service:jaeger
    restart: always
    ports:
      - 18673:18673
    networks:
      - my-network

  ts-inside-payment-mongo:
    image: mongo
    networks:
      - my-network

  ts-execute-service:
    image: maruftuhin/ts-execute-service:jaeger
    restart: always
    ports:
      - 12386:12386
    networks:
      - my-network

  ts-payment-service:
    image: maruftuhin/ts-payment-service:jaeger
    restart: always
    ports:
      - 19001:19001
    networks:
      - my-network

  ts-payment-mongo:
    image: mongo
    networks:
      - my-network

  ts-rebook-service:
    image: maruftuhin/ts-rebook-service:jaeger
    restart: always
    ports:
      - 18886:18886
    networks:
      - my-network

  ts-rebook-mongo:
    image: mongo
    networks:
      - my-network

  ts-cancel-service:
    image: maruftuhin/ts-cancel-service:jaeger
    restart: always
    ports:
      - 18885:18885
    networks:
      - my-network

  ts-assurance-service:
    image: maruftuhin/ts-assurance-service:jaeger
    restart: always
    ports:
      - 18888:18888
    networks:
      - my-network

  ts-assurance-mongo:
    image: mongo
    networks:
      - my-network

  ts-seat-service:
    image: maruftuhin/ts-seat-service:jaeger
    restart: always
    ports:
      - 18898:18898
    networks:
      - my-network

  ts-travel-plan-service:
    image: maruftuhin/ts-travel-plan-service:jaeger
    restart: always
    ports:
      - 14322:14322
    networks:
      - my-network

  # Written in JavaScript
  ts-ticket-office-service:
    image: maruftuhin/ts-ticket-office-service:jaeger
    restart: always
    ports:
      - 16108:16108
    networks:
      - my-network

  ts-ticket-office-mongo:
    image: mongo
    networks:
      - my-network

  # Written in GO
  ts-news-service:
    image: maruftuhin/ts-news-service:jaeger
    restart: always
    ports:
      - 12862:12862
    networks:
      - my-network

  ts-news-mongo:
    image: mongo
    networks:
      - my-network

  ts-voucher-mysql:
    image: mysql
    expose:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    networks:
      - my-network

  # Written in Python
  ts-voucher-service:
    image: maruftuhin/ts-voucher-service:jaeger
    restart: always
    ports:
      - 16101:16101
    depends_on:
      - ts-voucher-mysql
    volumes:
      - /var/lib/mysql
    networks:
      - my-network

  ts-food-map-service:
    image: maruftuhin/ts-food-map-service:jaeger
    restart: always
    ports:
      - 18855:18855
    networks:
      - my-network

  ts-food-map-mongo:
    image: mongo
    networks:
      - my-network

  ts-route-plan-service:
    image: maruftuhin/ts-route-plan-service:jaeger
    restart: always
    ports:
      - 14578:14578
    networks:
      - my-network

  ts-food-service:
    image: maruftuhin/ts-food-service:jaeger
    restart: always
    ports:
      - 18856:18856
    networks:
      - my-network

  ts-consign-service:
    image: maruftuhin/ts-consign-service:jaeger
    restart: always
    ports:
      - 16111:16111
    networks:
      - my-network

  ts-consign-mongo:
    image: mongo
    networks:
      - my-network

  ts-consign-price-service:
    image: maruftuhin/ts-consign-price-service:jaeger
    restart: always
    ports:
      - 16110:16110
    networks:
      - my-network

  ts-consign-price-mongo:
    image: mongo
    networks:
      - my-network

  ts-food-mongo:
    image: mongo
    networks:
      - my-network

  ts-admin-basic-info-service:
    image: maruftuhin/ts-admin-basic-info-service:jaeger
    restart: always
    ports:
      - 18767:18767
    networks:
      - my-network

  ts-admin-order-service:
    image: maruftuhin/ts-admin-order-service:jaeger
    restart: always
    ports:
      - 16112:16112
    networks:
      - my-network

  ts-admin-route-service:
    image: maruftuhin/ts-admin-route-service:jaeger
    restart: always
    ports:
      - 16113:16113
    networks:
      - my-network

  ts-admin-travel-service:
    image: maruftuhin/ts-admin-travel-service:jaeger
    restart: always
    ports:
      - 16114:16114
    networks:
      - my-network

  ts-admin-user-service:
    image: maruftuhin/ts-admin-user-service:jaeger
    restart: always
    ports:
      - 16115:16115
    networks:
      - my-network

  ts-avatar-service:
    image: maruftuhin/ts-avatar-service:jaeger
    restart: always
    ports:
      - 17001:17001
    networks:
      - my-network

  jaeger:
    image: jaegertracing/all-in-one:1.15
    ports:
      - 16686:16686
    networks:
      - my-network

networks:
  my-network:
    # driver: overlay
    driver: bridge

